#What Is Pooling in Convolutional Neural Networks

Pooling can be considered analogous to **pixel-Binning** in photography. In Binning we consolidate a small kernel of pixels into a single pixel. The Kernel applies a **`max`** or **`mean`** operation over the the Kernel to convert into one singular pixel. The binning process reduces N pixels to 1, causing a reduction in resolution, but improves SNR

So in 2x2 binning 4 adjacent pixels are converted to 1 via average or max operation

In CNN context, a Pooling Layer reduces the size of **feature maps (outputs on convolution layers**  by binning adjacent maps ( pixels in this analogy). It in turn reduces the computational load of a CNN and improves feature sensitivity


There are two main types of pooling
* **Average Pooling** `tf.keras.layers.MaxPoolXD`
* **Max Pooling** `tf.keras.layers.AveragePoolingXD`

In [29]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [30]:
tf.random.set_seed(42)
X = tf.random.uniform(shape=(6,6),minval=1, maxval=20,dtype=tf.int32)

# a 2D pooling macro expects a RANK-4 tensor with the following dimensions
#
#  data_format="channels_last" => (batch_size, height, width, channels)
#  data_format="channels_first" =>  (batch_size, channels, height, width)
#
X = tf.reshape(X,[1,6,6,1])
tf.squeeze(X)

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[19,  4,  1,  3,  2,  9],
       [11,  1,  6, 18,  2, 10],
       [ 6, 17, 10,  9, 14,  7],
       [ 8, 10, 12,  7,  3,  9],
       [19,  6, 11,  1, 15,  1],
       [13,  1, 17, 11,  7,  5]], dtype=int32)>

## Max Pooling
See [tensorflow docs](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPool2D)

In [31]:
MaxPoolLayer=tf.keras.layers.MaxPool2D(pool_size=2,strides=2)
Y = MaxPoolLayer(X)
tf.squeeze(X),tf.squeeze(Y)

(<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
 array([[19,  4,  1,  3,  2,  9],
        [11,  1,  6, 18,  2, 10],
        [ 6, 17, 10,  9, 14,  7],
        [ 8, 10, 12,  7,  3,  9],
        [19,  6, 11,  1, 15,  1],
        [13,  1, 17, 11,  7,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[19, 18, 10],
        [17, 12, 14],
        [19, 17, 15]], dtype=int32)>)

🔑 Note that the Pooled output contains MAX values over a 2x2 window over the input, The size of the output is reduced dramatically

## Average Pooling
See [tensorflow docs](https://www.tensorflow.org/api_docs/python/tf/keras/layers/AveragePooling2D)

In [27]:
AvgPoolLayer=tf.keras.layers.AveragePooling2D(pool_size=2,strides=2)
Z = AvgPoolLayer(tf.cast(X,tf.float32))
tf.squeeze(X),tf.squeeze(Z)

(<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
 array([[19,  4,  1,  3,  2,  9],
        [11,  1,  6, 18,  2, 10],
        [ 6, 17, 10,  9, 14,  7],
        [ 8, 10, 12,  7,  3,  9],
        [19,  6, 11,  1, 15,  1],
        [13,  1, 17, 11,  7,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 8.75,  7.  ,  5.75],
        [10.25,  9.5 ,  8.25],
        [ 9.75, 10.  ,  7.  ]], dtype=float32)>)

In [28]:
((19+4+11+1) / 4),tf.squeeze(Z)[0,0]

(8.75, <tf.Tensor: shape=(), dtype=float32, numpy=8.75>)

🔑 Note that the Pooled output contains AVERAGED values over a 2x2 window over the input. The Size of the output is reduced dramatically